# Generated by Django 4.0.6 on 2022-07-07 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category_id', models.CharField(choices=[('1', 'Kebab'), ('2', 'Indian Food'), ('3', 'Swiss Food'), ('4', 'Columbian Food'), ('5', 'Peruvian Food'), ('6', 'Hot Dogs'), ('7', 'Italian Food')], max_length=20, verbose_name='category')),
                ('street', models.TextField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99950, 'The entered zip code is invalid.')])),
                ('country', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(max_length=30)),
                ('price_level', models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], default=1, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
