# Generated by Django 4.0.6 on 2022-07-08 13:46

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.user_directory_path),
        ),
    ]
