# Generated by Django 4.0.6 on 2022-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category_id',
            field=models.CharField(choices=[('1', 'Kebab'), ('2', 'Indian Food'), ('3', 'Swiss Food'), ('4', 'Columbian Food'), ('5', 'Peruvian Food'), ('6', 'Hot Dogs'), ('7', 'Italian Food'), ('8', 'Asian Food'), ('9', 'Ethiopian Food'), ('10', 'Japanese Food'), ('11', 'Fusion Food'), ('12', 'Veggies'), ('13', 'Only Meat'), ('14', 'Chinese Food'), ('15', 'Deutsch Food'), ('16', 'French Cuisine'), ('17', 'Brewery'), ('18', 'Mexican Food'), ('19', 'Afghanistan Food'), ('20', 'Moroccan Food'), ('21', 'Philippian Food')], max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
