name: luna-backend
dependencies:
    - python=3.10.4
    - pip=21.2.4
    - psycopg2=2.8.6
    - pip:
        - django==4.0.6
        - djangorestframework==3.13.1
        - djangorestframework-simplejwt==5.2.0
        - drf-yasg
        - django-filter
        - flake8==4.0.1
        - gunicorn==20.1.0
        - Pillow==9.1.1
        - django-cors-headers==3.13.0